name: CI

on:
  push: 
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ vars.PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DOCKER_PORT: 80
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.21.0"

      - name: Install Dependencies
        run: npm ci

      - name: Run App
        run: node src/server.js &

      - name: Check health
        run: curl "http://127.0.0.1:$PORT/health"  
        
      - name: Say Hello
        run: curl "http://127.0.0.1:$PORT/api/hello"  

      - name: Retrive Secret
        run: curl "http://127.0.0.1:$PORT/api/key"  

      - name: Build Docker Image
        run: docker build -t testnodejsapp:v1 .
      
      - name: List Docker Images
        run: docker images

      - name: Run Docker Container
        run: docker run -d --name testnodejsapp -p $DOCKER_PORT:$PORT -e SECRET_KEY=$SECRET_KEY -e PORT=$PORT testnodejsapp:v1

      - name: Check Health
        run: curl "http://127.0.0.1:$DOCKER_PORT/health"